"use client";
import React, { ReactNode, useState } from "react";
import { ChevronDown, ChevronUp, MapPin, Search } from "lucide-react";

// Brisbane and surrounding locations data
export const locations = [
  { name: "Abbotsbury", slug: "abbotsbury" },
  { name: "Acacia Gardens", slug: "acacia-gardens" },
  { name: "Agnes Banks", slug: "agnes-banks" },
  { name: "Airds", slug: "airds" },
  { name: "Ambarvale", slug: "ambarvale" },
  { name: "Arndell Park", slug: "arndell-park" },
  { name: "Austral", slug: "austral" },
  { name: "Sydney", slug: "sydney" },
  { name: "Parramatta", slug: "parramatta" },
  { name: "Liverpool", slug: "liverpool" },
  { name: "Blacktown", slug: "blacktown" },
  { name: "Penrith", slug: "penrith" },
  { name: "Campbelltown", slug: "campbelltown" },
  { name: "Camden", slug: "camden" },
  { name: "Oran Park", slug: "oran-park" },
  { name: "Narellan", slug: "narellan" },
  { name: "Glenmore Park", slug: "glenmore-park" },
  { name: "St Marys", slug: "st-marys" },
  { name: "Narellan Vale", slug: "narellan-vale" },
  { name: "Newtown", slug: "newtown" },
  { name: "Ashfield", slug: "ashfield" },
  { name: "Leichhardt", slug: "leichhardt" },
  { name: "Marrickville", slug: "marrickville" },
  { name: "Abbotsford", slug: "abbotsford" },
  { name: "Ashbury", slug: "ashbury" },
  { name: "Ashcroft", slug: "ashcroft" },
  { name: "Auburn", slug: "auburn" },
  { name: "Bondi", slug: "bondi" },
  { name: "Randwick", slug: "randwick" },
  { name: "Maroubra", slug: "maroubra" },
  { name: "Coogee", slug: "coogee" },
  { name: "Alexandria", slug: "alexandria" },
  { name: "Arncliffe", slug: "arncliffe" },
  { name: "Mount Druitt", slug: "mount-druitt" },
  { name: "Rooty Hill", slug: "rooty-hill" },
  { name: "Doonside", slug: "doonside" },
  { name: "Fairfield", slug: "fairfield" },
  { name: "Granville", slug: "granville" },
  { name: "Quakers Hill", slug: "quakers-hill" },
  { name: "Schofields", slug: "schofields" },
  { name: "Castle Hill", slug: "castle-hill" },
  { name: "Baulkham Hills", slug: "baulkham-hills" },
  { name: "Kellyville", slug: "kellyville" },
  { name: "Rouse Hill", slug: "rouse-hill" },
  { name: "The Ponds", slug: "the-ponds" },
  { name: "Leppington", slug: "leppington" },
  { name: "Edmondson Park", slug: "edmondson-park" },
  { name: "Cecil Hills", slug: "cecil-hills" },
  { name: "Badgerys Creek", slug: "badgerys-creek" },
  { name: "Wollongong", slug: "wollongong" },
  { name: "Fairy Meadow", slug: "fairy-meadow" },
  { name: "Shellharbour", slug: "shellharbour" },
  { name: "Dapto", slug: "dapto" },
  { name: "Corrimal", slug: "corrimal" },
  { name: "Figtree", slug: "figtree" },
  { name: "Albion Park", slug: "albion-park" },
  { name: "Austinmer", slug: "austinmer" },
  { name: "Balgownie", slug: "balgownie" },
  { name: "Bellambi", slug: "bellambi" },
  { name: "Berkeley", slug: "berkeley" },
  { name: "Bulli", slug: "bulli" },
  { name: "Coledale", slug: "coledale" },
  { name: "Coniston", slug: "coniston" },
  { name: "Helensburgh", slug: "helensburgh" },
  { name: "Kanahooka", slug: "kanahooka" },
  { name: "Keiraville", slug: "keiraville" },
  { name: "Mount Ousley", slug: "mount-ousley" },
  { name: "North Wollongong", slug: "north-wollongong" },
  { name: "Port Kembla", slug: "port-kembla" },
  { name: "Stanwell Park", slug: "stanwell-park" },
  { name: "Thirroul", slug: "thirroul" },
  { name: "Towradgi", slug: "towradgi" },
  { name: "Unanderra", slug: "unanderra" },
  { name: "Woonona", slug: "woonona" },
  { name: "Albion Park Rail", slug: "albion-park-rail" },
  { name: "Barrack Heights", slug: "barrack-heights" },
  { name: "Blackbutt", slug: "blackbutt" },
  { name: "Calderwood", slug: "calderwood" },
  { name: "Flinders", slug: "flinders" },
  { name: "Oak Flats", slug: "oak-Flats" },
  { name: "Shell Cove", slug: "shell-cove" },
  { name: "Warilla", slug: "warilla" },
  { name: "Windang", slug: "windang" },
  { name: "Bombo", slug: "bombo" },
  { name: "Foxground", slug: "foxground" },
  { name: "Gerringong", slug: "gerringong" },
  { name: "Jamberoo", slug: "jamberoo" },
  { name: "Berry", slug: "berry" },
  { name: "Bawley Point", slug: "bawley-point" },
  { name: "Culburra Beach", slug: "culburra-beach" },
  { name: "Gerroa", slug: "gerroa" },
  { name: "Huskisson", slug: "huskisson" },
  { name: "Kangaroo Valley", slug: "kangaroo-valley" },
  { name: "Milton", slug: "milton" },
  { name: "Mollymook", slug: "mollymook" },
  { name: "Nowra", slug: "nowra" },
  { name: "Shoalhaven Heads", slug: "shoalhaven-heads" },
  { name: "Ulladulla", slug: "ulladulla" },
  { name: "Katoomba", slug: "katoomba" },
  { name: "Springwood", slug: "springwood" },
  { name: "Blaxland", slug: "blaxland" },
  { name: "Glenbrook", slug: "glenbrook" },
  { name: "Lawson", slug: "lawson" },
  { name: "Balgowlah", slug: "balgowlah" },
  { name: "Balgowlah Heights", slug: "balgowlah-heights" },
  { name: "Balmain", slug: "balmain" },
  { name: "Balmain East", slug: "balmain-east" },
  { name: "Bangor", slug: "bangor" },
  { name: "Banksia", slug: "banksia" },
  { name: "Banksmeadow", slug: "banksmeadow" },
  { name: "Bankstown", slug: "bankstown" },
  { name: "Bankstown Aerodrome", slug: "bankstown-aerodrome" },
  { name: "Barangaroo", slug: "barangaroo" },
  { name: "Barden Ridge", slug: "barden-ridge" },
  { name: "Bardia", slug: "bardia" },
  { name: "Bardwell Park", slug: "bardwell-park" },
  { name: "Bardwell Valley", slug: "bardwell-valley" },
  { name: "Bass Hill", slug: "bass-hill" },
  { name: "Bayview", slug: "bayview" },
  { name: "Beacon Hill", slug: "beacon-hill" },
  { name: "Beaconsfield", slug: "beaconsfield" },
  { name: "Beaumont Hills", slug: "beaumont-hills" },
  { name: "Cremorne", slug: "cremorne" },
  { name: "Cremorne Point", slug: "cremorne-point" },
  { name: "Cromer", slug: "cromer" },
  { name: "Cronulla", slug: "cronulla" },
  { name: "Crows Nest", slug: "crows-est" },
  { name: "Croydon", slug: "croydon" },
  { name: "Croydon Park", slug: "croydon-park" },
  { name: "Curl Curl", slug: "curl-curl" },
  { name: "Currans Hill", slug: "currans-hill" },
  { name: "Currawong Beach", slug: "currawong-beach" },
  { name: "Daceyville", slug: "daceyville" },
  { name: "Dangar Island", slug: "dangar-island" },
  { name: "Darling Point", slug: "darling-point" },
  { name: "Darlinghurst", slug: "darlinghurst" },
  { name: "Darlington", slug: "darlington" },
  { name: "Davidson", slug: "davidson" },
  { name: "Dawes Point", slug: "dawes-point" },
  { name: "Dean Park", slug: "dean-park" },
  { name: "Dee Why", slug: "dee-why" },
  { name: "Denham Court", slug: "denham-dourt" },
  { name: "Denistone", slug: "denistone" },
  { name: "Denistone East", slug: "denistone-east" },
  { name: "Denistone West", slug: "denistone-eest" },
  { name: "Dharruk", slug: "dharruk" },
  { name: "Dolans Bay", slug: "dolans-bay" },
  { name: "Dolls Point", slug: "dolls-point" },
  { name: "Double Bay", slug: "double-bay" },
  { name: "Dover Heights", slug: "dover-heights" },
  { name: "Drummoyne", slug: "drummoyne" },
  { name: "Duffys Forest", slug: "duffys-forest" },
  { name: "Dulwich Hill", slug: "dulwich-hill" },
  { name: "Dundas", slug: "dundas" },
  { name: "Dundas Valley", slug: "dundas-valley" },
  { name: "Dural", slug: "dural" },
  //COMPLETE ^

  { name: "Eagle Vale", slug: "eagle-vale" },
  { name: "Earlwood", slug: "earlwood" },
  { name: "East Hills", slug: "east-hills" },
  { name: "East Killara", slug: "east-killara" },
  { name: "East Lindfield", slug: "east-lindfield" },
  { name: "East Ryde", slug: "east-ryde" },
  { name: "Eastern Creek", slug: "eastern-creek" },
  { name: "Eastgardens", slug: "eastgardens" },
  { name: "Eastlakes", slug: "eastlakes" },
  { name: "Eastwood", slug: "eastwood" },
  { name: "Edensor Park", slug: "edensor-park" },
  { name: "Kurnell", slug: "kurnell" },
  { name: "Kurraba Point", slug: "kurraba-point" },
  { name: "Kyeemagh", slug: "kyeemagh" },
  { name: "Kyle Bay", slug: "kyle-bay" },
  { name: "La Perouse", slug: "la-perouse" },
  { name: "Lakemba", slug: "lakemba" },
  { name: "Lalor Park", slug: "lalor-park" },
  { name: "Lane Cove", slug: "lane-cove" },
  { name: "Lane Cove North", slug: "lane-cove-north" },
  { name: "Lane Cove West", slug: "lane-cove-west" },
  { name: "Lansdowne", slug: "lansdowne" },
  { name: "Lansvale", slug: "lansvale" },
  { name: "Laughtondale", slug: "laughtondale" },
  { name: "Lavender Bay", slug: "lavender-bay" },
  { name: "Leets Vale", slug: "leets-vale" },
  { name: "Len Waters Estate", slug: "len-waters-estate" },
  { name: "Lethbridge Park", slug: "lethbridge-park" },
  { name: "Leumeah", slug: "leumeah" },
  { name: "Lewisham", slug: "lewisham" },
  { name: "Liberty Grove", slug: "liberty-grove" },
  { name: "Lidcombe", slug: "lidcombe" },
  { name: "Lilli Pilli", slug: "lilli-pilli" },
  { name: "Lilyfield", slug: "lilyfield" },
  { name: "Lindfield", slug: "lindfield" },
  { name: "Linley Point", slug: "linley-point" },
  { name: "Little Bay", slug: "little-bay" },
  { name: "Llandilo", slug: "llandilo" },
  { name: "Loftus", slug: "loftus" },
  { name: "Londonderry", slug: "londonderry" },
  { name: "Long Point", slug: "long-point" },
  { name: "Longueville", slug: "longueville" },
  { name: "Lovett Bay", slug: "lovett-bay" },
  { name: "Lower Portland", slug: "lower-portland" },
  { name: "Lucas Heights", slug: "lucas-heights" },
  { name: "Luddenham", slug: "luddenham" },
  { name: "Lugarno", slug: "lugarno" },
  { name: "Lurnea", slug: "lurnea" },
  { name: "Macquarie Fields", slug: "macquarie-fields" },
  { name: "Macquarie Links", slug: "macquarie-links" },
  { name: "Macquarie Park", slug: "macquarie-park" },
  { name: "Maianbar", slug: "maianbar" },
  { name: "Malabar", slug: "malabar" },
  { name: "Manly", slug: "manly" },
  { name: "Manly Vale", slug: "manly-vale" },
  { name: "Maraylya", slug: "maraylya" },
  { name: "Marayong", slug: "marayong" },
  { name: "Maroota", slug: "maroota" },
  { name: "Marsden Park", slug: "marsden-park" },
  { name: "Marsfield", slug: "marsfield" },
  { name: "Mascot", slug: "mascot" },
  { name: "Matraville", slug: "matraville" },
  { name: "Mays Hill", slug: "mays-hill" },
  { name: "McCarrs Creek", slug: "mccarrs-creek" },
  { name: "McGraths Hill", slug: "mcgraths-hill" },
  { name: "McMahons Point", slug: "mcmahons-point" },
  { name: "Meadowbank", slug: "meadowbank" },
  { name: "Melonba", slug: "melonba" },
  { name: "Melrose Park", slug: "melrose-park" },
  { name: "Menai", slug: "menai" },
  { name: "Menangle Park", slug: "menangle-park" },
  { name: "Merrylands", slug: "merrylands" },
  { name: "Merrylands West", slug: "merrylands-west" },
  { name: "Middle Cove", slug: "middle-cove" },
  { name: "Middle Dural", slug: "middle-dural" },
  { name: "Middleton Grange", slug: "middleton-grange" },
  { name: "Miller", slug: "miller" },
  { name: "Millers Point", slug: "millers-point" },
  { name: "Milperra", slug: "milperra" },
  { name: "Milsons Passage", slug: "milsons-passage" },
  { name: "Milsons Point", slug: "milsons-point" },
  { name: "Minchinbury", slug: "minchinbury" },
  { name: "Minto", slug: "minto" },
  { name: "Minto Heights", slug: "minto-heights" },
  { name: "Miranda", slug: "miranda" },
  { name: "Mona Vale", slug: "mona-vale" },
  { name: "Monterey", slug: "monterey" },
  { name: "Moore Park", slug: "moore-park" },
  { name: "Moorebank", slug: "moorebank" },
  { name: "Morning Bay", slug: "morning-bay" },
  { name: "Mortdale", slug: "mortdale" },
  { name: "Mortlake", slug: "mortlake" },
  { name: "Mosman", slug: "mosman" },
  //COMPLETE ^

  { name: "Mount Annan", slug: "mount-annan" },
  { name: "Mount Colah", slug: "mount-colah" },
  { name: "Mount Kuring-Gai", slug: "mount-kuring-gai" },
  { name: "Mount Lewis", slug: "mount-lewis" },
  { name: "Mount Pritchard", slug: "mount-pritchard" },
  { name: "Mount Vernon", slug: "mount-vernon" },
  { name: "Mulgoa", slug: "mulgoa" },
  { name: "Mulgrave", slug: "mulgrave" },
  { name: "Naremburn", slug: "naremburn" },
  { name: "Narrabeen", slug: "narrabeen" },
  { name: "Narraweena", slug: "narraweena" },
  { name: "Narwee", slug: "narwee" },
  { name: "Nelson", slug: "nelson" },
  { name: "Neutral Bay", slug: "neutral-bay" },
  { name: "Newington", slug: "newington" },
  { name: "Newport", slug: "newport" },
  { name: "Nirimba Fields", slug: "nirimba-fields" },
  { name: "Normanhurst", slug: "normanhurst" },
  { name: "North Balgowlah", slug: "north-balgowlah" },
  { name: "North Bondi", slug: "north-bondi" },
  { name: "North Curl Curl", slug: "north-curl-curl" },
  { name: "North Epping", slug: "north-epping" },
  { name: "North Kellyville", slug: "north-kellyville" },
  { name: "North Manly", slug: "north-manly" },
  { name: "North Narrabeen", slug: "north-narrabeen" },
  { name: "North Parramatta", slug: "north-parramatta" },
  { name: "North Rocks", slug: "north-rocks" },
  { name: "North Ryde", slug: "north-ryde" },
  { name: "North St Marys", slug: "north-st-marys" },
  { name: "North Strathfield", slug: "north-strathfield" },
  { name: "North Sydney", slug: "north-sydney" },
  { name: "North Turramurra", slug: "north-turramurra" },
  { name: "North Wahroonga", slug: "north-wahroonga" },
  { name: "North Willoughby", slug: "north-willoughby" },
  { name: "Northbridge", slug: "northbridge" },
  { name: "Northmead", slug: "northmead" },
  { name: "Northwood", slug: "northwood" },
  { name: "Norwest", slug: "norwest" },
  { name: "Oakhurst", slug: "oakhurst" },
  { name: "Oakville", slug: "oakville" },
  { name: "Oatlands", slug: "oatlands" },
  { name: "Oatley", slug: "oatley" },
  { name: "Old Guildford", slug: "old-guildford" },
  { name: "Old Toongabbie", slug: "old-toongabbie" },
  { name: "Orchard Hills", slug: "orchard-hills" },
  { name: "Oxford Falls", slug: "oxford-falls" },
  { name: "Oxley Park", slug: "oxley-park" },
  { name: "Oyster Bay", slug: "oyster-bay" },
  { name: "Paddington", slug: "paddington" },
  { name: "Padstow", slug: "padstow" },
  { name: "Padstow Heights", slug: "padstow-heights" },
  { name: "Pagewood", slug: "pagewood" },
  { name: "Palm Beach", slug: "palm-beach" },
  { name: "Panania", slug: "panania" },
  { name: "Parklea", slug: "parklea" },
  { name: "Peakhurst", slug: "peakhurst" },
  { name: "Peakhurst Heights", slug: "peakhurst-heights" },
  { name: "Pemulwuy", slug: "pemulwuy" },
  { name: "Pendle Hill", slug: "pendle-hill" },
  { name: "Pennant Hills", slug: "pennant-hills" },
  { name: "Penshurst", slug: "penshurst" },
  { name: "Petersham", slug: "petersham" },
  { name: "Phillip Bay", slug: "phillip-bay" },
  { name: "Picnic Point", slug: "picnic-point" },
  { name: "Pitt Town", slug: "pitt-town" },
  { name: "Pleasure Point", slug: "pleasure-point" },
  { name: "Plumpton", slug: "plumpton" },
  { name: "Point Piper", slug: "point-piper" },
  { name: "Port Botany", slug: "port-botany" },
  { name: "Port Hacking", slug: "port-hacking" },
  { name: "Potts Hill", slug: "potts-hill" },
  { name: "Potts Point", slug: "potts-point" },
  { name: "Prairiewood", slug: "prairiewood" },
  { name: "Prestons", slug: "prestons" },
  { name: "Prospect", slug: "prospect" },
  { name: "Punchbowl", slug: "punchbowl" },
  { name: "Putney", slug: "putney" },
  { name: "Pymble", slug: "pymble" },
  { name: "Pyrmont", slug: "pyrmont" },
  { name: "Queens Park", slug: "queens-park" },
  { name: "Queenscliff", slug: "queenscliff" },
  { name: "Raby", slug: "raby" },
  { name: "Ramsgate", slug: "ramsgate" },
  { name: "Ramsgate Beach", slug: "ramsgate-beach" },
  { name: "Redfern", slug: "redfern" },
  { name: "Regents Park", slug: "regents-park" },
  { name: "Regentville", slug: "regentville" },
  { name: "Revesby", slug: "revesby" },
  { name: "Revesby Heights", slug: "revesby-heights" },
  { name: "Rhodes", slug: "rhodes" },
  { name: "Richards", slug: "richards" },
  { name: "Richmond", slug: "richmond" },
  { name: "Riverstone", slug: "riverstone" },
  { name: "Riverview", slug: "riverview" },
  { name: "Riverwood", slug: "riverwood" },
  { name: "Rockdale", slug: "rockdale" },
  { name: "Rodd Point", slug: "rodd-point" },
  { name: "Rookwood", slug: "rookwood" },
  { name: "Ropes Crossing", slug: "ropes-crossing" },
  //COMPLETE ^

  { name: "Rose Bay", slug: "rose-bay" },
  { name: "Rosebery", slug: "rosebery" },
  { name: "Rosehill", slug: "rosehill" },
  { name: "Roselands", slug: "roselands" },
  { name: "Rosemeadow", slug: "rosemeadow" },
  { name: "Roseville", slug: "roseville" },
  { name: "Roseville Chase", slug: "roseville-chase" },
  { name: "Rossmore", slug: "rossmore" },
  { name: "Rozelle", slug: "rozelle" },
  { name: "Ruse", slug: "ruse" },
  { name: "Rushcutters Bay", slug: "rushcutters-bay" },
  { name: "Russell Lea", slug: "russell-lea" },
  { name: "Rydalmere", slug: "rydalmere" },
  { name: "Ryde", slug: "ryde" },
  { name: "Sackville North", slug: "sackville-north" },
  { name: "Sadleir", slug: "sadleir" },
  { name: "Sandringham", slug: "sandringham" },
  { name: "Sandy Point", slug: "sandy-point" },
  { name: "Sans Souci", slug: "sans-souci" },
  { name: "Scotland Island", slug: "scotland-island" },
  { name: "Seaforth", slug: "seaforth" },
  { name: "Sefton", slug: "sefton" },
  { name: "Seven Hills", slug: "seven-hills" },
  { name: "Shalvey", slug: "shalvey" },
  { name: "Shanes Park", slug: "shanes-park" },
  { name: "Silverwater", slug: "silverwater" },
  { name: "Singletons Mill", slug: "singletons-mill" },
  { name: "Smeaton Grange", slug: "smeaton-grange" },
  { name: "Smithfield", slug: "smithfield" },
  { name: "South Coogee", slug: "south-coogee" },
  { name: "South Granville", slug: "south-granville" },
  { name: "South Hurstville", slug: "south-hurstville" },
  { name: "South Maroota", slug: "south-maroota" },
  { name: "South Penrith", slug: "south-penrith" },
  { name: "South Turramurra", slug: "south-turramurra" },
  { name: "South Wentworthville", slug: "south-wentworthville" },
  { name: "South Windsor", slug: "south-windsor" },
  { name: "Spring Farm", slug: "spring-farm" },
  { name: "St Andrews", slug: "st-andrews" },
  { name: "St Clair", slug: "st-clair" },
  { name: "St Helens Park", slug: "st-helens-park" },
  { name: "St Ives", slug: "st-ives" },
  { name: "St Ives Chase", slug: "st-ives-chase" },
  { name: "St Johns Park", slug: "st-johns-park" },
  { name: "St Leonards", slug: "st-leonards" },
  { name: "St Peters", slug: "st-peters" },
  { name: "Stanhope Gardens", slug: "stanhope-gardens" },
  { name: "Stanmore", slug: "stanmore" },
  { name: "Strathfield", slug: "strathfield" },
  { name: "Strathfield South", slug: "strathfield-south" },
  { name: "Summer Hill", slug: "summer-hill" },
  { name: "Surry Hills", slug: "surry-hills" },
  { name: "Sutherland", slug: "sutherland" },
  { name: "Sydenham", slug: "sydenham" },
  { name: "Sydney Olympic Park", slug: "sydney-olympic-park" },
  { name: "Sylvania", slug: "sylvania" },
  { name: "Sylvania Waters", slug: "sylvania-waters" },
  { name: "Tallawong", slug: "tallawong" },
  { name: "Tamarama", slug: "tamarama" },
  { name: "Taren Point", slug: "taren-point" },
  { name: "Telopea", slug: "telopea" },
  { name: "Tempe", slug: "tempe" },
  { name: "Tennyson Point", slug: "tennyson-point" },
  { name: "Terrey Hills", slug: "terrey-hills" },
  { name: "The Rocks", slug: "the-rocks" },
  { name: "Thornleigh", slug: "thornleigh" },
  { name: "Toongabbie", slug: "toongabbie" },
  { name: "Tregear", slug: "tregear" },
  { name: "Turramurra", slug: "turramurra" },
  { name: "Turrella", slug: "turrella" },
  { name: "Ultimo", slug: "ultimo" },
  { name: "Varroville", slug: "varroville" },
  { name: "Vaucluse", slug: "vaucluse" },
  { name: "Villawood", slug: "villawood" },
  { name: "Vineyard", slug: "vineyard" },
  { name: "Voyager Point", slug: "voyager-point" },
  { name: "Wahroonga", slug: "wahroonga" },
  { name: "Waitara", slug: "waitara" },
  { name: "Wakeley", slug: "wakeley" },
  { name: "Wareemba", slug: "wareemba" },
  { name: "Warrawee", slug: "warrawee" },
  { name: "Warriewood", slug: "warriewood" },
  { name: "Warwick Farm", slug: "warwick-farm" },
  { name: "Waterfall", slug: "waterfall" },
  { name: "Waterloo", slug: "waterloo" },
  { name: "Watsons Bay", slug: "watsons-bay" },
  { name: "Wattle Grove", slug: "wattle-grove" },
  { name: "Waverley", slug: "waverley" },
  { name: "Waverton", slug: "waverton" },
  { name: "Wedderburn", slug: "wedderburn" },
  { name: "Wentworth Point", slug: "wentworth-point" },
  { name: "Wentworthville", slug: "wentworthville" },
  { name: "Werrington", slug: "werrington" },
  { name: "Werrington County", slug: "werrington-county" },
  { name: "Werrington Downs", slug: "werrington-downs" },
  { name: "West Hoxton", slug: "west-hoxton" },
  { name: "West Pennant Hills", slug: "west-pennant-hills" },
  { name: "West Pymble", slug: "west-pymble" },
  //COMPLETE

  { name: "West Ryde", slug: "west-ryde" },
  { name: "Westleigh", slug: "westleigh" },
  { name: "Westmead", slug: "westmead" },
  { name: "Wetherill Park", slug: "wetherill-park" },
  { name: "Whalan", slug: "whalan" },
  { name: "Whale Beach", slug: "whale-beach" },
  { name: "Wheeler Heights", slug: "wheeler-heights" },
  { name: "Wiley Park", slug: "wiley-park" },
  { name: "Willmot", slug: "willmot" },
  { name: "Willoughby", slug: "willoughby" },
  { name: "Willoughby East", slug: "willoughby-east" },
  { name: "Windsor", slug: "windsor" },
  { name: "Windsor Downs", slug: "windsor-downs" },
  { name: "Winston Hills", slug: "winston-hills" },
  { name: "Wisemans Ferry", slug: "wisemans-ferry" },
  { name: "Wolli Creek", slug: "wolli-creek" },
  { name: "Wollstonecraft", slug: "wollstonecraft" },
  { name: "Woodbine", slug: "woodbine" },
  { name: "Woodcroft", slug: "woodcroft" },
  { name: "Woodpark", slug: "woodpark" },
  { name: "Woollahra", slug: "woollahra" },
  { name: "Woolloomooloo", slug: "woolloomooloo" },
  { name: "Woolooware", slug: "woolooware" },
  { name: "Woolwich", slug: "woolwich" },
  { name: "Woronora", slug: "woronora" },
  { name: "Woronora Heights", slug: "woronora-heights" },
  { name: "Yagoona", slug: "yagoona" },
  { name: "Yarrawarrah", slug: "yarrawarrah" },
  { name: "Yennora", slug: "yennora" },
  { name: "Yowie Bay", slug: "yowie-bay" },
  { name: "Zetland", slug: "zetland" },
  { name: "Edgecliff", slug: "edgecliff" },
  { name: "Elanora Heights", slug: "elanora-heights" },
  { name: "Elderslie", slug: "elderslie" },
  { name: "Elizabeth Bay", slug: "elizabeth-bay" },
  { name: "Elizabeth Hills", slug: "elizabeth-hills" },
  { name: "Elvina Bay", slug: "elvina-bay" },
  { name: "Emerton", slug: "emerton" },
  { name: "Enfield", slug: "enfield" },
  { name: "Engadine", slug: "engadine" },
  { name: "Englorie Park", slug: "englorie-park" },
  { name: "Enmore", slug: "enmore" },
  { name: "Epping", slug: "epping" },
  { name: "Ermington", slug: "ermington" },
  { name: "Erskine Park", slug: "erskine-park" },
  { name: "Erskineville", slug: "erskineville" },
  { name: "Eschol Park", slug: "eschol-park" },
  { name: "Eveleigh", slug: "eveleigh" },
  { name: "Fairfield East", slug: "fairfield-east" },
  { name: "Fairfield Heights", slug: "fairfield-heights" },
  { name: "Fairfield West", slug: "fairfield-west" },
  { name: "Fairlight", slug: "fairlight" },
  { name: "Fiddletown", slug: "fiddletown" },
  { name: "Five Dock", slug: "five-dock" },
  { name: "Forest Glen", slug: "forest-glen" },
  { name: "Forest Lodge", slug: "forest-lodge" },
  { name: "Forestville", slug: "forestville" },
  { name: "Frenchs Forest", slug: "frenchs-forest" },
  { name: "Freshwater", slug: "freshwater" },
  { name: "Gables", slug: "gables" },
  { name: "Galston", slug: "galston" },
  { name: "Georges Hall", slug: "georges-hall" },
  { name: "Gilead", slug: "gilead" },
  { name: "Girraween", slug: "girraween" },
  { name: "Gladesville", slug: "gladesville" },
  { name: "Glebe", slug: "glebe" },
  { name: "Gledswood Hills", slug: "gledswood-hills" },
  { name: "Glen Alpine", slug: "glen-alpine" },
  { name: "Glendenning", slug: "glendenning" },
  { name: "Glenfield", slug: "glenfield" },
  //COMPLETE ^

  { name: "Glenhaven", slug: "glenhaven" },
  { name: "Glenorie", slug: "glenorie" },
  { name: "Glenwood", slug: "glenwood" },
  { name: "Gordon", slug: "gordon" },
  { name: "Grantham Farm", slug: "grantham-farm" },
  { name: "Grays Point", slug: "grays-point" },
  { name: "Great Mackerel Beach", slug: "great-mackerel-beach" },
  { name: "Green Valley", slug: "green-valley" },
  { name: "Greenacre", slug: "greenacre" },
  { name: "Greendale", slug: "greendale" },
  { name: "Greenfield Park", slug: "greenfield-park" },
  { name: "Greenhills Beach", slug: "greenhills-beach" },
  { name: "Greenwich", slug: "greenwich" },
  { name: "Gregory Hills", slug: "gregory-hills" },
  { name: "Greystanes", slug: "greystanes" },
  { name: "Guildford", slug: "guildford" },
  { name: "Guildford West", slug: "guildford-west" },
  { name: "Gymea", slug: "gymea" },
  { name: "Gymea Bay", slug: "gymea-bay" },
  { name: "Haberfield", slug: "haberfield" },
  { name: "Hammondville", slug: "hammondville" },
  { name: "Harrington Park", slug: "harrington-park" },
  { name: "Harris Park", slug: "harris-park" },
  { name: "Hassall Grove", slug: "hassall-grove" },
  { name: "Haymarket", slug: "haymarket" },
  { name: "Heathcote", slug: "heathcote" },
  { name: "Hebersham", slug: "hebersham" },
  { name: "Heckenberg", slug: "heckenberg" },
  { name: "Henley", slug: "henley" },
  { name: "Hillsdale", slug: "hillsdale" },
  { name: "Hinchinbrook", slug: "hinchinbrook" },
  { name: "Hobartville", slug: "hobartville" },
  { name: "Holroyd", slug: "holroyd" },
  { name: "Holsworthy", slug: "holsworthy" },
  { name: "Homebush", slug: "homebush" },
  { name: "Homebush West", slug: "homebush-west" },
  { name: "Horningsea Park", slug: "horningsea-park" },
  { name: "Hornsby", slug: "hornsby" },
  { name: "Hornsby Heights", slug: "hornsby-heights" },
  { name: "Horsley Park", slug: "horsley-park" },
  { name: "Hoxton Park", slug: "hoxton-park" },
  { name: "Hunters Hill", slug: "hunters-hill" },
  { name: "Huntingwood", slug: "huntingwood" },
  { name: "Huntleys Cove", slug: "huntleys-cove" },
  { name: "Huntleys Point", slug: "huntleys-point" },
  { name: "Hurlstone Park", slug: "hurlstone-park" },
  { name: "Hurstville", slug: "hurstville" },
  { name: "Hurstville Grove", slug: "hurstville-grove" },
  { name: "Illawong", slug: "illawong" },
  { name: "Ingleburn", slug: "ingleburn" },
  { name: "Ingleside", slug: "ingleside" },
  { name: "Jamisontown", slug: "jamisontown" },
  { name: "Jannali", slug: "jannali" },
  { name: "Jordan Springs", slug: "jordan-springs" },
  { name: "Kangaroo Point", slug: "kangaroo-point" },
  { name: "Kareela", slug: "kareela" },
  { name: "Kearns", slug: "kearns" },
  { name: "Kellyville Ridge", slug: "kellyville-ridge" },
  { name: "Kemps Creek", slug: "kemps-creek" },
  { name: "Kensington", slug: "kensington" },
  { name: "Kenthurst", slug: "kenthurst" },
  { name: "Kentlyn", slug: "kentlyn" },
  { name: "Killara", slug: "killara" },
  { name: "Killarney Heights", slug: "killarney-heights" },
  { name: "Kings Langley", slug: "kings-langley" },
  { name: "Kings Park", slug: "kings-park" },
  { name: "Kingsford", slug: "kingsford" },
  { name: "Kingsgrove", slug: "kingsgrove" },
  { name: "Kingswood", slug: "kingswood" },
  { name: "Kirkham", slug: "kirkham" },
  { name: "Kirrawee", slug: "kirrawee" },
  { name: "Kirribilli", slug: "kirribilli" },
  { name: "Kogarah", slug: "kogarah" },
  { name: "Kogarah Bay", slug: "kogarah-bay" },
  { name: "Ku-ring-gai Chase", slug: "ku-ring-gai-chase" },
  { name: "Beecroft", slug: "beecroft" },
  { name: "Belfield", slug: "belfield" },
  //COMPLETE ^

  { name: "Bella Vista", slug: "bella-vista" },
  { name: "Bellevue Hill", slug: "bellevue-hill" },
  { name: "Belmore", slug: "belmore" },
  { name: "Belrose", slug: "belrose" },
  { name: "Berala", slug: "berala" },
  { name: "Berkshire Park", slug: "berkshire-park" },
  { name: "Berowra", slug: "berowra" },
  { name: "Berowra Heights", slug: "berowra-heights" },
  { name: "Berowra Waters", slug: "berowra-waters" },
  { name: "Berrilee", slug: "berrilee" },
  { name: "Beverley Park", slug: "beverley-park" },
  { name: "Beverly Hills", slug: "beverly-hills" },
  { name: "Bexley", slug: "bexley" },
  { name: "Bexley North", slug: "bexley-north" },
  { name: "Bidwill", slug: "bidwill" },
  { name: "Bilgola Beach", slug: "bilgola-beach" },
  { name: "Bilgola Plateau", slug: "bilgola-plateau" },
  { name: "Birchgrove", slug: "birchgrove" },
  { name: "Birrong", slug: "birrong" },
  { name: "Blackett", slug: "blackett" },
  { name: "Blair Athol", slug: "blair-athol" },
  { name: "Blairmount", slug: "blairmount" },
  { name: "Blakehurst", slug: "blakehurst" },
  { name: "Bligh Park", slug: "bligh-park" },
  { name: "Bondi Beach", slug: "bondi-beach" },
  { name: "Bondi Junction", slug: "bondi-junction" },
  { name: "Bonnet Bay", slug: "bonnet-bay" },
  { name: "Bonnyrigg", slug: "bonnyrigg" },
  { name: "Bonnyrigg Heights", slug: "bonnyrigg-heights" },
  { name: "Bossley Park", slug: "bossley-park" },
  { name: "Botany", slug: "botany" },
  { name: "Bow Bowing", slug: "bow-bowing" },
  { name: "Box Hill", slug: "box-hill" },
  { name: "Bradbury", slug: "bradbury" },
  { name: "Bradfield", slug: "bradfield" },
  { name: "Breakfast Point", slug: "breakfast-point" },
  { name: "Brighton-Le-Sands", slug: "brighton-le-sands" },
  { name: "Bringelly", slug: "bringelly" },
  { name: "Bronte", slug: "bronte" },
  { name: "Brooklyn", slug: "brooklyn" },
  { name: "Brookvale", slug: "brookvale" },
  { name: "Bundeena", slug: "bundeena" },
  { name: "Bungarribee", slug: "bungarribee" },
  { name: "Burraneer", slug: "burraneer" },
  { name: "Burwood", slug: "burwood" },
  { name: "Burwood Heights", slug: "burwood-heights" },
  { name: "Busby", slug: "busby" },
  { name: "Cabarita", slug: "cabarita" },
  { name: "Cabramatta", slug: "cabramatta" },
  { name: "Cabramatta West", slug: "cabramatta-west" },
  { name: "Caddens", slug: "caddens" },
  { name: "Cambridge Gardens", slug: "cambridge-gardens" },
  { name: "Cambridge Park", slug: "cambridge-park" },
  { name: "Camellia", slug: "camellia" },
  { name: "Cammeray", slug: "cammeray" },
  { name: "Camperdown", slug: "camperdown" },
  { name: "Campsie", slug: "campsie" },
  { name: "Canada Bay", slug: "canada-bay" },
  { name: "Canley Heights", slug: "canley-heights" },
  { name: "Canley Vale", slug: "canley-vale" },
  { name: "Canoelands", slug: "canoelands" },
  { name: "Canterbury", slug: "canterbury" },
  { name: "Caringbah", slug: "caringbah" },
  { name: "Caringbah South", slug: "caringbah-south" },
  { name: "Carlingford", slug: "carlingford" },
  { name: "Carlton", slug: "carlton" },
  { name: "Carnes Hill", slug: "carnes-hill" },
  { name: "Carramar", slug: "carramar" },
  { name: "Carss Park", slug: "carss-park" },
  { name: "Cartwright", slug: "cartwright" },
  { name: "Castle Cove", slug: "castle-cove" },
  { name: "Castlecrag", slug: "castlecrag" },
  { name: "Castlereagh", slug: "castlereagh" },
  { name: "Casula", slug: "casula" },
  { name: "Catherine Field", slug: "catherine-field" },
  { name: "Cattai", slug: "cattai" },
  { name: "Cecil Park", slug: "cecil-park" },
  { name: "Centennial Park", slug: "centennial-park" },
  { name: "Chatswood", slug: "chatswood" },
  { name: "Chatswood West", slug: "chatswood-west" },
  { name: "Cheltenham", slug: "cheltenham" },
  { name: "Cherrybrook", slug: "cherrybrook" },
  { name: "Chester Hill", slug: "chester-hill" },
  { name: "Chifley", slug: "chifley" },
  { name: "Chippendale", slug: "chippendale" },
  { name: "Chipping Norton", slug: "chipping-norton" },
  { name: "Chiswick", slug: "chiswick" },
  //Complete

  { name: "Chullora", slug: "chullora" },
  { name: "Church Point", slug: "church-point" },
  { name: "Claremont Meadows", slug: "claremont-meadows" },
  { name: "Clarendon", slug: "clarendon" },
  { name: "Clareville", slug: "clareville" },
  { name: "Claymore", slug: "claymore" },
  { name: "Clemton Park", slug: "clemton-park" },
  { name: "Clontarf", slug: "clontarf" },
  { name: "Clovelly", slug: "clovelly" },
  { name: "Clyde", slug: "clyde" },
  { name: "Coasters Retreat", slug: "coasters-retreat" },
  { name: "Cobbitty", slug: "cobbitty" },
  { name: "Colebee", slug: "colebee" },
  { name: "Collaroy", slug: "collaroy" },
  { name: "Collaroy Plateau", slug: "collaroy-plateau" },
  { name: "Colyton", slug: "colyton" },
  { name: "Como", slug: "como" },
  { name: "Concord", slug: "concord" },
  { name: "Concord West", slug: "concord-west" },
  { name: "Condell Park", slug: "condell-park" },
  { name: "Connells Point", slug: "connells-point" },
  { name: "Constitution Hill", slug: "constitution-hill" },
  { name: "Cottage Point", slug: "cottage-point" },
  { name: "Cowan", slug: "cowan" },
  { name: "Cranebrook", slug: "cranebrook" },
  { name: "Akuna Bay", slug: "akuna-bay" },
  { name: "Allambie", slug: "allambie" },
  { name: "Argyle Cut", slug: "argyle-cut" },
  { name: "Avalon Beach", slug: "avalon-beach" },
  { name: "Bald Face", slug: "bald-face" },
  { name: "Balmoral", slug: "balmoral" },
  { name: "Bantry Bay", slug: "bantry-bay" },
  { name: "Barra Brui", slug: "barra-brui" },
  { name: "Bardwell Valley", slug: "bardwell-valley" },
  { name: "Beauty Point", slug: "beauty-point" },
  { name: "Ben Buckler", slug: "ben-buckler" },
  { name: "Blacktown Industrial Area", slug: "blacktown-industrial-area" },
  { name: "Blaxlands Corner", slug: "blaxlands-corner" },
  { name: "Broadway", slug: "broadway" },
  { name: "Bungaroo", slug: "bungaroo" },
  { name: "Caravan Head", slug: "caravan-head" },
  { name: "Careel Bay", slug: "careel-bay" },
  {
    name: "Centennial Parklands Dining Precinct",
    slug: "centennial-parklands-dining-precinct",
  },
  {
    name: "Centennial Parklands Entertainment Quarter",
    slug: "centennial-parklands-entertainment-quarter",
  },
  {
    name: "Centennial Parklands Office Precinct",
    slug: "centennial-parklands-office-precinct",
  },
  { name: "Centennial Square", slug: "centennial-square" },
  { name: "Central", slug: "central" },
  { name: "Charing Cross", slug: "charing-cross" },
  { name: "Chatsworth", slug: "chatsworth" },
  { name: "Chinatown", slug: "chinatown" },
  { name: "Church Hill", slug: "church-hill" },
  { name: "Clifton Gardens", slug: "clifton-gardens" },
  { name: "Cliftonville", slug: "cliftonville" },
  { name: "Coba Point", slug: "coba-point" },
  { name: "Collaroy Beach", slug: "collaroy-beach" },
  { name: "Corr Neighbourhood Centre", slug: "corr-neighbourhood-centre" },
  { name: "Cremorne Junction", slug: "cremorne-junction" },
  { name: "Crestwood", slug: "crestwood" },
  { name: "Cromer Heights", slug: "cromer-heights" },
  { name: "Crosslands", slug: "crosslands" },
  { name: "Darling Square", slug: "darling-square" },
  { name: "Dee Why Beach", slug: "dee-why-beach" },
  { name: "Diamond Bay", slug: "diamond-bay" },
  { name: "Dobroyd Point", slug: "dobroyd-point" },
  { name: "Dunheved", slug: "dunheved" },
  { name: "East St Ives", slug: "east-st-ives" },
  { name: "East Sydney", slug: "east-sydney" },
  { name: "East Wahroonga", slug: "east-wahroonga" },
  { name: "Equality Green", slug: "equality-green" },
  { name: "Fishermans Beach", slug: "fishermans-beach" },
  { name: "Five Ways", slug: "five-ways" },
  { name: "Flemington", slug: "flemington" },
  { name: "Forestville Bend", slug: "forestville-bend" },
  { name: "Fox Studios", slug: "fox-studios" },
  { name: "Fox Valley", slug: "fox-valley" },
  { name: "Fullers Bridge", slug: "fullers-bridge" },
  { name: "Gallows Hill", slug: "gallows-hill" },
  { name: "Georges Heights", slug: "georges-heights" },
  { name: "Golden Grove", slug: "golden-grove" },
  { name: "Gooseberry Flat", slug: "gooseberry-flat" },
  { name: "Gore Hill", slug: "gore-hill" },
  { name: "Hewitt Hillside", slug: "hewitt-hillside" },
  { name: "Jack Mundey Place", slug: "jack-mundey-place" },
  { name: "Kings Cross", slug: "kings-cross" },
  { name: "Kingswood Park", slug: "kingswood-park" },
  { name: "Lemongrove", slug: "lemongrove" },
  { name: "Little Greece", slug: "little-greece" },
  { name: "Little Italy", slug: "little-italy" },
  { name: "Little Portugal", slug: "little-portugal" },
  { name: "Little Vietnam", slug: "little-vietnam" },
  { name: "Long Reef", slug: "long-reef" },
  { name: "Macdonaldtown", slug: "macdonaldtown" },
  { name: "Maroubra Junction", slug: "maroubra-junction" },
  { name: "Melville", slug: "melville" },
  { name: "Mill Hill", slug: "mill-hill" },
  { name: "Mobbs Hill", slug: "mobbs-hill" },
  { name: "Mosman Junction", slug: "mosman-junction" },
  { name: "Mosmans Bay", slug: "mosmans-bay" },
  //Complete ^

  { name: "Mount Pleasant", slug: "mount-pleasant" },
  { name: "Murray Farm", slug: "murray-farm" },
  { name: "Narrabeen Peninsula", slug: "narrabeen-peninsula" },
  { name: "Neutral Bay Junction", slug: "neutral-bay-junction" },
  { name: "Newport Beach", slug: "newport-beach" },
  { name: "North St Ives", slug: "north-st-ives" },
  { name: "Paradise Beach", slug: "paradise-beach" },
  { name: "Park Central", slug: "park-central" },
  { name: "Peach Trees", slug: "peach-trees" },
  { name: "Pearces Corner (Blacktown)", slug: "pearces-corner-blacktown" },
  { name: "Pearces Corner (Hornsby)", slug: "pearces-corner-hornsby" },
  { name: "Penrith Park", slug: "penrith-park" },
  { name: "Peryman Square", slug: "peryman-square" },
  { name: "Pyes Crossing", slug: "pyes-crossing" },
  { name: "Quarry Hill", slug: "quarry-hill" },
  { name: "Queens Square", slug: "queens-square" },
  { name: "Rose Bay North", slug: "rose-bay-north" },
  { name: "Round Corner", slug: "round-corner" },
  { name: "Ryde Central", slug: "ryde-central" },
  { name: "Shorts Corner", slug: "shorts-corner" },
  { name: "Sorlie", slug: "sorlie" },
  { name: "Spit Junction", slug: "spit-junction" },
  { name: "Strawberry Hills", slug: "strawberry-hills" },
  { name: "Sunny Corner", slug: "sunny-corner" },
  { name: "Sydney Olympic Park", slug: "sydney-olympic-park" },
  { name: "Taylor Square", slug: "taylor-square" },
  { name: "The Basin", slug: "the-basin" },
  { name: "The Hungry Mile", slug: "the-hungry-mile" },
  { name: "The Spit", slug: "the-spit" },
  { name: "The University Of Sydney", slug: "the-university-of-sydney" },
  { name: "The Warren", slug: "the-warren" },
  { name: "Thompsons Corner", slug: "thompsons-corner" },
  { name: "Three Saints Square", slug: "three-saints-square" },
  { name: "Town Hall", slug: "town-hall" },
  { name: "Victoria Cross", slug: "victoria-cross" },
  { name: "Walsh Bay", slug: "walsh-bay" },
  { name: "Washington Park", slug: "washington-park" },
  { name: "Wingala", slug: "wingala" },
  { name: "Wynyard", slug: "wynyard" },
  { name: "Bullaburra", slug: "bullaburra" },
  { name: "Blackheath", slug: "blackheath" },
  {
    name: "Blue Mountains National Park",
    slug: "blue-mountains-national-park",
  },
  { name: "Braemar", slug: "braemar" },
  { name: "Clarence", slug: "clarence" },
  { name: "Emu Heights", slug: "emu-heights" },
  { name: "Faulconbridge", slug: "faulconbridge" },
  { name: "Leura", slug: "leura" },
  { name: "Linden", slug: "linden" },
  { name: "Medlow Bath", slug: "medlow-bath" },
  { name: "Mount Riverview", slug: "mount-riverview" },
  { name: "Mount Victoria", slug: "mount-victoria" },
  { name: "Sun Valley", slug: "sun-valley" },
  { name: "Valley Heights", slug: "valley-heights" },
  { name: "Wentworth Falls", slug: "wentworth-falls" },
  { name: "Winmalee", slug: "winmalee" },
  { name: "Warrimoo", slug: "warrimoo" },
  { name: "Woodford", slug: "woodford" },
  { name: "Hazelbrook", slug: "hazelbrook" },
  { name: "Lapstone", slug: "lapstone" },
  { name: "Mount Wilson", slug: "mount-wilson" },
  { name: "Mount Irvine", slug: "mount-irvine" },
  { name: "Mount York", slug: "mount-york" },
  { name: "Megalong Valley", slug: "megalong-valley" },
  { name: "Mount Tomah", slug: "mount-tomah" },
  { name: "Bell", slug: "bell" },
  { name: "Mount Hay", slug: "mount-hay" },
  { name: "Newnes Plateau", slug: "newnes-plateau" },
  { name: "Hartley Vale", slug: "hartley-vale" },
  { name: "Little Hartley", slug: "little-hartley" },
  { name: "Hartley", slug: "hartley" },
  { name: "Bowenfels", slug: "bowenfels" },
  { name: "Glenbrook Heights", slug: "glenbrook-heights" },
  { name: "Lennox Bridge", slug: "lennox-bridge" },
  { name: "Yellow Rock", slug: "yellow-rock" },
] as const;

const groupedLocations = {
  "Greater Sydney": [
    "Sydney",
    "Parramatta",
    "Liverpool",
    "Blacktown",
    "Penrith",
    "Campbelltown",
    "Camden",
    "Oran Park",
    "Narellan",
    "Glenmore Park",
    "St Marys",
    "Narellan Vale",
    "Eastwood",
    "Marsfield",
    "Melrose Park",
    "Denistone",
    "Denistone East",
    "Denistone West",
    "Liberty Grove",
    "Meadowbank",
    "Mays Hill",
    "Lidcombe",
    "Mount Annan",
    "Mount Lewis",
    "Mount Pritchard",
    "Mount Vernon",
    "Mulgoa",
    "Mulgrave",
    "Newington",
    "Nirimba Fields",
    "North Parramatta",
    "North Rocks",
    "North Ryde",
    "North St Marys",
    "Northmead",
    "Norwest",
    "Oakhurst",
    "Oakville",
    "Oatlands",
    "Old Guildford",
    "Old Toongabbie",
    "Orchard Hills",
    "Oxley Park",
    "Parklea",
    "Pemulwuy",
    "Pendle Hill",
    "Pennant Hills",
    "Plumpton",
    "Prospect",
    "Pitt Town",
    "Ropes Crossing",
    "Riverstone",
    "Regentville",
    "Glenhaven",
    "Glenorie",
    "Glenwood",
    "Grantham Farm",
    "Green Valley",
    "Greenacre",
    "Greendale",
    "Greenfield Park",
    "Gregory Hills",
    "Greystanes",
    "Guildford",
    "Guildford West",
    "Hammondville",
    "Harris Park",
    "Hassall Grove",
    "Hebersham",
    "Heckenberg",
    "Henley",
    "Hinchinbrook",
    "Hobartville",
    "Holroyd",
    "Holsworthy",
    "Homebush",
    "Homebush West",
    "Horningsea Park",
    "Huntingwood",
    "Hoxton Park",
    "Illawong",
    "Ingleburn",
    "Jordan Springs",
    "Kareela",
    "Kearns",
    "Kellyville Ridge",
    "Kemps Creek",
    "Kentlyn",
    "Kings Langley",
    "Kings Park",
    "Kingswood",
    "Kirkham",
    "Kogarah",
    "Kogarah Bay",
    "Belfield",
    "Belmore",
    "Clarendon",
    "Colyton",
    "Constitution Hill",
    "Cowan",
    "Cliftonville",
    "Fox Studios",
    "Equality Green",
    "Crosslands",
    "Mobbs Hill",
    "Gore Hill",
    "Jack Mundey Place",
    "Golden Grove",
    "Gooseberry Flat",
    "Hewitt Hillside",
    "Central",
    "Argyle Cut",
    "Little Greece",
    "Little Italy",
    "Little Portugal",
    "Little Vietnam",
    "Corr Neighbourhood Centre",
    "Birrong",
    "Botany",
    "Carlingford",
    "Camellia",
    "Carramar",
    "Cheltenham",
    "Chester Hill",
    "Chipping Norton",
    "Canoelands",
    "Cattai",
    "Strawberry Hills",
    "Taylor Square",
    "Town Hall",
    "Wynyard",
    "Walsh Bay",
    "Victoria Cross",
    "Queens Square",
  ],

  "Inner West Sydney": [
    "Newtown",
    "Ashfield",
    "Marrickville",
    "Abbotsford",
    "Ashbury",
    "Balmain",
    "Balmain East",
    "Croydon",
    "Croydon Park",
    "Earlwood",
    "Lilyfield",
    "Mortlake",
    "Drummoyne",
    "Dulwich Hill",
    "Summer Hill",
    "Petersham",
    "Leichhardt",
    "Annandale",
    "Stanmore",
    "Surry Hills",
    "Tempe",
    "Sydenham",
    "St Peters",
    "Waterloo",
    "Ultimo",
    "Darlington",
    "Burwood",
    "Burwood Heights",
    "Camperdown",
    "Canterbury",
    "Campsie",
    "Chiswick",
    "Breakfast Point",
    "Cabarita",
    "Canada Bay",
    "Clyde",
    "Concord",
    "Concord West",
    "Clemton Park",
    "Dobroyd Point",
    "Five Ways",
    "Broadway",
    "Macdonaldtown",
    "Chinatown",
    "Enfield",
    "Enmore",
    "Eveleigh",
    "Eschol Park",
    "Glebe",
    "The Rocks",
    "Redfern",
    "Rozelle",
    "Russell Lea",
    "Haberfield",
    "Hurlstone Park",
    "Lewisham",
  ],

  "Eastern Suburbs": [
    "Bondi",
    "Randwick",
    "Coogee",
    "Alexandria",
    "Beaconsfield",
    "Daceyville",
    "Darling Point",
    "Darlinghurst",
    "Double Bay",
    "Dover Heights",
    "Eastgardens",
    "Eastlakes",
    "Little Bay",
    "La Perouse",
    "Malabar",
    "Matraville",
    "Mascot",
    "Moore Park",
    "Paddington",
    "Potts Point",
    "Point Piper",
    "Kyeemagh",
    "Maroubra",
    "Phillip Bay",
    "North Bondi",
    "Queens Park",
    "Queenscliff",
    "Bellevue Hill",
    "Bondi Beach",
    "Bondi Junction",
    "Bronte",
    "Centennial Park",
    "Chifley",
    "Rose Bay North",
    "Paradise Beach",
    "The Basin",
    "Clovelly",
    "Maroubra Junction",
    "Pagewood",
    "Kurnell",
    "Charing Cross",
    "Diamond Bay",
    "Ben Buckler",
    "Tamarama",
    "Centennial Parklands Dining Precinct",
    "Centennial Parklands Entertainment Quarter",
    "Centennial Parklands Office Precinct",
    "Centennial Square",
    "East Sydney",
    "Darling Square",
    "Kings Cross",
    "Rose Bay",
    "Rosebery",
    "Rushcutters Bay",
    "South Coogee",
    "Vaucluse",
    "Watsons Bay",
    "Waverley",
    "Woollahra",
    "Edgecliff",
    "Elizabeth Bay",
    "Elvina Bay",
    "Fairlight",
    "Woolloomooloo",
    "Zetland",
    "Hillsdale",
    "Kensington",
    "Kingsford",
  ],

  "North Shore": [
    "Cremorne",
    "Crows Nest",
    "Darlington",
    "Denistone",
    "Denistone East",
    "Denistone West",
    "East Killara",
    "Lane Cove",
    "Lane Cove North",
    "Lane Cove West",
    "Longueville",
    "Cremorne Point",
    "Kurraba Point",
    "McMahons Point",
    "Lavender Bay",
    "Middle Cove",
    "Berowra",
    "Berowra Heights",
    "Berowra Waters",
    "Berrilee",
    "Chatswood",
    "Chatswood West",
    "Cheltenham",
    "Mosman",
    "Mosman Junction",
    "Cremorne Junction",
    "Neutral Bay",
    "Kirribilli",
    "Waverton",
    "Milsons Point",
    "Clifton Gardens",
    "Balmoral",
    "Beauty Point",
    "Georges Heights",
    "Mosmans Bay",
    "Wollstonecraft",
    "St Leonards",
    "Cammeray",
    "Chatsworth",
    "East Lindfield",
    "Fox Valley",
    "Fullers Bridge",
    "Barra Brui",
    "East Wahroonga",
    "Normanhurst",
    "Pymble",
    "St Ives",
    "St Ives Chase",
    "Wahroonga",
    "Killara",
    "Gordon",
    "Lindfield",
    "Castle Cove",
    "Castlecrag",
    "North Sydney",
    "Naremburn",
    "North Willoughby",
    "Northwood",
    "North Turramurra",
    "North Wahroonga",
    "Northbridge",
    "Roseville",
    "Roseville Chase",
    "Ryde",
    "Tamarama",
    "Turramurra",
    "Waitara",
    "Warrawee",
    "Warriewood",
    "West Pymble",
    "Seaforth",
    "Thornleigh",
    "Terrey Hills",
    "Neutral Bay Junction",
    "North St Ives",
    "The Spit",
    "Spit Junction",
    "Sorlie",
    "Killarney Heights",
    "Ku-ring-gai Chase",
    "Beecroft",
  ],
  "Northern Sydney": [
    "West Ryde",
    "Westleigh",
    "Wheeler Heights",
    "Willoughby",
    "Willoughby East",
    "Woolwich",
    "Wollstonecraft",
    "Elanora Heights",
    "Epping",
    "Ermington",
    "Forestville",
    "Frenchs Forest",
    "Freshwater",
    "Galston",
    "Gladesville",
    "Pearces Corner",
    "Ryde Central",
  ],

  "Northern Beaches": [
    "Balgowlah",
    "Balgowlah Heights",
    "Bayview",
    "Beacon Hill",
    "Cromer",
    "Curl Curl",
    "Dee Why",
    "Davidson",
    "Duffys Forest",
    "Manly",
    "Manly Vale",
    "Mona Vale",
    "Lovett Bay",
    "Morning Bay",
    "Currawong Beach",
    "Bilgola Beach",
    "Bilgola Plateau",
    "Brookvale",
    "Newport",
    "Newport Beach",
    "Narrabeen Peninsula",
    "Wingala",
    "Avalon Beach",
    "Clareville",
    "Church Point",
    "Collaroy",
    "Collaroy Plateau",
    "Collaroy Beach",
    "Dee Why Beach",
    "Coasters Retreat",
    "Fishermans Beach",
    "Long Reef",
    "Palm Beach",
    "Careel Bay",
    "Cottage Point",
    "Queenscliff",
    "Fairlight",
    "Allambie",
    "Cromer Heights",
    "McCarrs Creek",
    "Narrabeen",
    "Narraweena",
    "North Manly",
    "North Balgowlah",
    "North Curl Curl",
    "North Narrabeen",
    "North Turramurra",
    "North Wahroonga",
    "South Turramurra",
    "Seaforth",
    "Warriewood",
    "Scotland Island",
    "Middle Dural",
  ],

  "Hills District": [
    "Castle Hill",
    "Rouse Hill",
    "The Ponds",
    "Beaumont Hills",
    "Middle Dural",
    "Maraylya",
    "Maroota",
    "Round Corner",
    "Thompsons Corner",
    "Quarry Hill",
    "Dural",
    "Kellyville Ridge",
    "Box Hill",
    "Castle Cove",
    "Castlecrag",
    "Cherrybrook",
    "Crestwood",
    "Baulkham Hills",
    "Norwest",
    "Bella Vista",
    "Winston Hills",
    "North Kellyville",
    "Kellyville",
    "West Pennant Hills",
  ],

  "Western Sydney": [
    "Mount Druitt",
    "Doonside",
    "Fairfield",
    "Granville",
    "Quakers Hill",
    "Schofields",
    "Arndell Park",
    "Airds",
    "Ambarvale",
    "Austral",
    "Dean Park",
    "Eastern Creek",
    "Minchinbury",
    "Marsden Park",
    "Melonba",
    "Lethbridge Park",
    "Dharruk",
    "Eagle Vale",
    "Edensor Park",
    "Lurnea",
    "Macquarie Fields",
    "Macquarie Links",
    "Minto",
    "Minto Heights",
    "Old Toongabbie",
    "Plumpton",
    "Pemulwuy",
    "Pendle Hill",
    "Regentville",
    "Ropes Crossing",
    "Rosehill",
    "Seven Hills",
    "St Clair",
    "St Marys",
    "Strathfield South",
    "Toongabbie",
    "Werrington",
    "Werrington County",
    "Werrington Downs",
    "West Pennant Hills",
    "Wentworthville",
    "South Wentworthville",
    "South Granville",
    "South Windsor",
    "Vineyard",
    "Sydney Olympic Park",
    "Wentworth Point",
    "Epping",
    "Ermington",
    "Five Dock",
    "Girraween",
    "Forest Glen",
    "Forest Lodge",
    "Gables",
    "Galston",
    "Georges Hall",
    "Frenchs Forest",
    "Forestville",
    "Luddenham",
    "Mulgoa",
    "Prospect",
    "Berala",
    "Berkshire Park",
    "Bidwill",
    "Blackett",
    "Pearces Corner (Blacktown)",
    "Penrith Park",
    "Park Central",
    "Washington Park",
    "Peach Trees",
    "Pyes Crossing",
    "Shorts Corner",
    "Bligh Park",
    "Bossley Park",
    "Bungarribee",
    "Canley Vale",
    "Canley Heights",
    "Carramar",
    "Casula",
    "Colyton",
    "Cranebrook",
    "Claremont Meadows",
    "Dunheved",
    "Kingswood Park",
    "Lalor Park",
    "Rooty Hill",
    "Blacktown Industrial Area",
    "Cecil Park",
    "Caddens",
    "Cambridge Gardens",
    "Cambridge Park",
    "Castlereagh",
  ],

  "South Sydney & Sutherland Shire": [
    "South Hurstville",
    "Sylvania",
    "Sylvania Waters",
    "Taren Point",
    "Sutherland",
    "Waterfall",
    "Engadine",
    "Woronora",
    "Woronora Heights",
    "Yarrawarrah",
    "Woolooware",
    "Yowie Bay",
    "Padstow Heights",
  ],

  "Western & South-West Outer Sydney": [
    "Singletons Mill",
    "Ropes Crossing",
    "Rydalmere",
    "Pendle Hill",
    "Telopea",
    "Wentworth Point",
    "Oxley Park",
    "South Penrith",
    "Bringelly",
    "Bradfield",
    "Catherine Field",
    "Cecil Park",
    "Caddens",
  ],

  "South West Sydney": [
    "Leppington",
    "Edmondson Park",
    "Cecil Hills",
    "Badgerys Creek",
    "Ashcroft",
    "Bardia",
    "Denham Court",
    "Currans Hill",
    "Edensor Park",
    "Lurnea",
    "Miller",
    "Moorebank",
    "Middleton Grange",
    "Macquarie Links",
    "Eagle Vale",
    "Luddenham",
    "Long Point",
    "Mount Annan",
    "Campbelltown",
    "Raby",
    "Minto",
    "Minto Heights",
    "Menangle Park",
    "Narellan",
    "Narellan Vale",
    "Rosemeadow",
    "Rossmore",
    "Ruse",
    "Sadleir",
    "Sefton",
    "Shalvey",
    "Shanes Park",
    "Smeaton Grange",
    "Smithfield",
    "Spring Farm",
    "St Andrews",
    "St Helens Park",
    "St Johns Park",
    "Tregear",
    "Varroville",
    "Villawood",
    "Wakeley",
    "Warwick Farm",
    "Wedderburn",
    "West Hoxton",
    "Elderslie",
    "Emerton",
    "Englorie Park",
    "Erskine Park",
    "Gilead",
    "Gledswood Hills",
    "Glen Alpine",
    "Glendenning",
    "Glenfield",
    "Fairfield East",
    "Fairfield Heights",
    "Fairfield West",
    "Elizabeth Hills",
    "Woodcroft",
    "Woodbine",
    "Whalan",
    "Willmot",
    "Yennora",
    "Hoxton Park",
    "Horsley Park",
    "Kemps Creek",
    "Kentlyn",
    "Ingleburn",
    "Macquarie Fields",
    "Oran Park",
    "Blair Athol",
    "Cobbitty",
    "Claymore",
    "Condell Park",
    "East Hills",
    "Revesby",
    "Padstow",
    "Padstow Heights",
    "Milperra",
    "Chullora",
    "Lansvale",
    "Fairfield",
    "Wetherill Park",
    "Leumeah",
    "Prestons",
    "Casula",
    "Blairmount",
    "Bradbury",
    "Mount Pleasant",
    "Murray Farm",
    "Sunny Corner",
    "Three Saints Square",
    "The Warren",
    "Bow Bowing",
    "Busby",
    "Carnes Hill",
    "Cartwright",
    "Catherine Field",
    "Cabramatta",
    "Cabramatta West",
    "Canley Heights",
    "Canley Vale",
  ],

  "St George & Sutherland": [
    "Arncliffe",
    "Bangor",
    "Banksia",
    "Banksmeadow",
    "Bankstown",
    "Bankstown Aerodrome",
    "Barden Ridge",
    "Bardwell Park",
    "Bardwell Valley",
    "Bass Hill",
    "Cronulla",
    "Dolans Bay",
    "Dolls Point",
    "Kurnell",
    "Kyle Bay",
    "Kyeemagh",
    "Loftus",
    "Menai",
    "Miranda",
    "Maianbar",
    "Monterey",
    "Beverley Park",
    "Bexley",
    "Bexley North",
    "Blakehurst",
    "Bonnet Bay",
    "Burraneer",
    "Carlton",
    "Connells Point",
    "Como",
    "Caravan Head",
    "Bald Face",
    "Peakhurst",
    "Peakhurst Heights",
    "Riverwood",
    "Mortdale",
    "Beverly Hills",
    "Lilli Pilli",
    "Port Hacking",
    "Caringbah",
    "Caringbah South",
    "Taren Point",
    "Carss Park",
    "Padstow",
    "Padstow Heights",
    "Panania",
    "Oatley",
    "Lugarno",
    "Penshurst",
    "Oyster Bay",
    "Kogarah",
    "Gymea",
    "Gymea Bay",
    "Kangaroo Point",
    "Kirrawee",
  ],

  "Wollongong & Illawarra": [
    "Wollongong",
    "Fairy Meadow",
    "Shellharbour",
    "Dapto",
    "Corrimal",
    "Figtree",
    "Albion Park",
    "Austinmer",
    "Balgownie",
    "Bellambi",
    "Berkeley",
    "Bulli",
    "Coledale",
    "Coniston",
    "Helensburgh",
    "Kanahooka",
    "Keiraville",
    "Mount Ousley",
    "North Wollongong",
    "Port Kembla",
    "Stanwell Park",
    "Thirroul",
    "Towradgi",
    "Unanderra",
    "Woonona",
    "Albion Park Rail",
    "Barrack Heights",
    "Blackbutt",
    "Calderwood",
    "Flinders",
    "Oak Flats",
    "Shell Cove",
    "Warilla",
    "Windang",
    "Bombo",
    "Foxground",
    "Gerringong",
    "Jamberoo",
    "Berry",
    "Bawley Point",
    "Culburra Beach",
    "Gerroa",
    "Huskisson",
    "Kangaroo Valley",
    "Milton",
    "Mollymook",
    "Nowra",
    "Shoalhaven Heads",
    "Ulladulla",
    "Grays Point",
    "Maianbar",
    "Bundeena",
  ],

  "Blue Mountains": [
    "Katoomba",
    "Springwood",
    "Blaxland",
    "Glenbrook",
    "Lawson",
    "Mulgoa",
    "Laughtondale",
    "Lower Portland",
    "Leets Vale",
    "Leura",
    "Wentworth Falls",
    "Bullaburra",
    "Blackheath",
    "Blue Mountains National Park",
    "Clarence",
    "Emu Heights",
    "Faulconbridge",
    "Linden",
    "Medlow Bath",
    "Mount Riverview",
    "Mount Victoria",
    "Sun Valley",
    "Valley Heights",
    "Winmalee",
    "Warrimoo",
    "Woodford",
    "Hazelbrook",
    "Lapstone",
    "Mount Wilson",
    "Mount Irvine",
    "Mount York",
    "Megalong Valley",
    "Mount Tomah",
    "Bell",
    "Mount Hay",
    "Newnes Plateau",
    "Hartley Vale",
    "Little Hartley",
    "Hartley",
    "Bowenfels",
    "Glenbrook Heights",
    "Lennox Bridge",
    "Yellow Rock",
    "Braemar",
  ],

  "Central Coast": [
    "Dangar Island",
    "McCarrs Creek",
    "Morning Bay",
    "Mona Vale",
    "Newport",
    "North Narrabeen",
    "Brooklyn",
    "Moore Park",
    "Coasters Retreat", // technically Hawkesbury River region, but close to Central Coast classification
  ],
};

type Region =
  | "Greater Sydney"
  | "Central Coast"
  | "St George & Sutherland"
  | "Hills District"
  | "South Sydney & Sutherland Shire"
  | "South West Sydney"
  | "Western & South-West Outer Sydney"
  | ""
  | "Northern Beaches"
  | "Inner West Sydney"
  | "North Shore"
  | "Northern Sydney"
  | "Eastern Suburbs"
  | "Western Sydney"
  | "Hills District"
  | "Wollongong & Illawarra"
  | "Blue Mountains";

export default function MobileLocationService() {
  // Use Partial<Record<Region, boolean>> so keys are optional
  const [expandedRegions, setExpandedRegions] = useState<
    Partial<Record<Region, boolean>>
  >({});
  const [searchTerm, setSearchTerm] = useState("");
  const [viewMode, setViewMode] = useState<"accordion" | "grid">("accordion");

  const toggleRegion = (region: Region) => {
    setExpandedRegions((prev) => ({
      ...prev,
      [region]: !prev[region],
    }));
  };

  const filteredGroupedLocations = searchTerm
    ? Object.entries(groupedLocations).reduce(
        (acc, [region, cities]) => {
          const regionMatches = region
            .toLowerCase()
            .includes(searchTerm.toLowerCase());
          const matchedCities = cities.filter((city) =>
            city.toLowerCase().includes(searchTerm.toLowerCase())
          );

          if (regionMatches || matchedCities.length > 0) {
            acc[region] = regionMatches ? cities : matchedCities;
          }

          return acc;
        },
        {} as Record<string, string[]>
      )
    : groupedLocations;

  type LinkProps = {
    href: string;
    children: ReactNode;
    className?: string;
  };

  const Link = ({ href, children, className }: LinkProps) => (
    <a href={href} className={className}>
      {children}
    </a>
  );

  return (
    <div className="max-w-4xl mx-auto p-4 space-y-6">
      {/* Header with search and view toggle */}
      <div className="space-y-4">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
          <input
            type="text"
            placeholder="Search locations or regions..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500 focus:border-transparent"
          />
        </div>

        <div className="flex gap-2">
          <button
            onClick={() => setViewMode("accordion")}
            className={`px-4 py-2 rounded-lg font-medium transition-colors ${
              viewMode === "accordion"
                ? "bg-red-600 text-white"
                : "bg-gray-100 text-gray-700 hover:bg-gray-200"
            }`}
          >
            Accordion View
          </button>
          <button
            onClick={() => setViewMode("grid")}
            className={`px-4 py-2 rounded-lg font-medium transition-colors ${
              viewMode === "grid"
                ? "bg-red-600 text-white"
                : "bg-gray-100 text-gray-700 hover:bg-gray-200"
            }`}
          >
            Grid View
          </button>
        </div>
      </div>

      {/* Accordion View */}
      {viewMode === "accordion" && (
        <div className="space-y-3">
          {Object.entries(filteredGroupedLocations).map(([region, cities]) => (
            <div
              key={region}
              className="border border-gray-200 rounded-lg overflow-hidden"
            >
              <button
                onClick={() => toggleRegion(region as Region)}
                className="w-full px-4 py-4 bg-white hover:bg-gray-50 flex items-center justify-between transition-colors"
              >
                <div className="flex items-center">
                  <div className="flex-shrink-0 w-3 h-3 bg-red-600 rounded-full mr-3"></div>
                  <h3 className="text-lg font-semibold text-gray-900">
                    {region}
                  </h3>
                  <span className="ml-2 text-sm text-gray-500">
                    ({cities.length})
                  </span>
                </div>
                {expandedRegions[region as Region] ? (
                  <ChevronUp className="w-5 h-5 text-gray-400" />
                ) : (
                  <ChevronDown className="w-5 h-5 text-gray-400" />
                )}
              </button>

              {expandedRegions[region as Region] && (
                <div className="px-4 pb-4 bg-gray-50 border-t border-gray-200">
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mt-3">
                    {cities.map((city) => {
                      const location = locations.find(
                        (loc) => loc.name === city
                      );
                      return location ? (
                        <Link
                          key={location.slug}
                          href={`/all-services?location=${location.slug.toLowerCase()}`}
                          className="flex items-center px-3 py-2 rounded-lg text-sm font-medium text-gray-700 bg-white hover:bg-red-600 hover:text-white border border-gray-200 hover:border-red-600 transition-all duration-200 hover:shadow-sm"
                        >
                          <MapPin className="w-4 h-4 mr-2 flex-shrink-0" />
                          {location.name}
                        </Link>
                      ) : null;
                    })}
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Grid View */}
      {viewMode === "grid" && (
        <div className="space-y-6">
          {Object.entries(filteredGroupedLocations).map(([region, cities]) => (
            <div key={region}>
              <div className="flex items-center mb-4">
                <div className="w-3 h-3 bg-red-600 rounded-full mr-3"></div>
                <h3 className="text-lg font-semibold text-gray-900">
                  {region}
                </h3>
                <span className="ml-2 text-sm text-gray-500">
                  ({cities.length})
                </span>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
                {cities.map((city) => {
                  const location = locations.find((loc) => loc.name === city);
                  return location ? (
                    <Link
                      key={location.slug}
                      href={`/all-services/${location.slug}`}
                      className="flex items-center px-4 py-3 rounded-lg text-sm font-medium text-gray-700 bg-white hover:bg-red-600 hover:text-white border border-gray-200 hover:border-red-600 transition-all duration-200 hover:shadow-sm"
                    >
                      <MapPin className="w-4 h-4 mr-2 flex-shrink-0" />
                      {location.name}
                    </Link>
                  ) : null;
                })}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* No results message */}
      {Object.keys(filteredGroupedLocations).length === 0 && (
        <div className="text-center py-12">
          <div className="text-gray-400 mb-2">
            <Search className="w-12 h-12 mx-auto" />
          </div>
          <p className="text-gray-500">
            No locations found matching &rdquo;{searchTerm}&ldquo;
          </p>
        </div>
      )}
    </div>
  );
}
